### ISSUE TITLE
gradle-lombok plugin is not working in a single project

### ISSUE THREAD

**Issue by wbsouza** [franzbecker/gradle-lombok#12]
I created a [post on stackoverflow](http://stackoverflow.com/questions/39609120/gradle-lombok-plugin-is-not-working-in-a-single-project) and it seems everything is right but the plugin still does not generate getters/setters methods. Thanks in advance for your efforts to share this plugin with the community.

**Comment by franzbecker** [comment]
Hey there, sorry for the late reply - I was on vacation. I'll have a look in the next couple of days.

**Comment by franzbecker** [comment]
I posted the answer on Stackoverflow, this is not an issue with this plugin but with the customization of the Java compiler arguments. The same problem occurs when you use Lombok without this plugin. Hope that helps you to go on!
