### ISSUE TITLE
Use gradle-lombok plugin when running under Jenkins

### ISSUE THREAD

**Issue by amarjeet** [franzbecker/gradle-lombok#15]
I am using gradle-lombok plugin and when invoked during a gradle build, the build is stuck forever with the following last console log:

```
Browse to https://projectlombok.org for more information. To install lombok on Eclipse, re-run this jar file on a graphical computer system - this message is being shown because your terminal is not graphics capable.
Alternatively, use the command line installer (java -jar lombok.jar install --help).
If you are just using 'javac' or a tool that calls on javac, no installation is neccessary; just make sure lombok.jar is in the classpath when you compile. Example:

   java -cp lombok.jar MyCode.java
```

How can this plugin run without opening up the lombok spring installer in a headless environment?

**Comment by franzbecker** [comment]
Could you provide more information such as which Gradle task you are calling and how your build configuration looks like?

From your descriptions it sounds like a configuration problem, not an issue with the plugin.

**Comment by amarjeet** [comment]
Here is how I have it configured:

In the `buildScript {}` section:

```
    dependencies {
        classpath "io.franzbecker:gradle-lombok:1.8"
    }
```

For each project:
```
allprojects {
    apply plugin: "io.franzbecker.gradle-lombok"

    lombok {
        version = "1.16.14"
        sha256 = ""
    }
}
```

When build is executing from within Jenkins, this swing application shows up:

![screen shot 2017-03-08 at 11 04 02 am](https://cloud.githubusercontent.com/assets/24115/23691559/39a3ab14-03ef-11e7-98d4-3b5cc2a7b93d.jpg)

Considering that Jenkins runs on a headless machine and there is no human intervention to deal with a swing application, I would like to know as to how can I prevent this from happening, so that the build does not pause forever.

Thanks

**Comment by franzbecker** [comment]
The dialog should only show up when calling the installLombok task. Is it possible that it is invoked? In Jenkins this should not be done / is not necessary as it only installs Lombok as a Java agent into a user's Eclipse IDE.

**Comment by amarjeet** [comment]
My guess is that it is indeed called automatically. The `installLombok` and `verifyLombok` tasks are registered by the plugin. Is it that these tasks get invoked when `gradle build` is executed? Plugins do hook into the compilation cycle of a project and it might be the case there.

I am specifically not invoking these tasks.

Thanks

**Comment by franzbecker** [comment]
These tasks should not hook into the regular guild cycle. Can you execute gradle tasks --all and find out what is going on?

**Comment by amarjeet** [comment]
The task list is:

```
Application tasks
-----------------
easy-cover-api:bootRun - Run the project with support for auto-detecting main class and reloading static resources

Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
generateSwaggerCode - Generates a source code from the swagger specification.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.

Verification tasks
------------------
check - Runs all checks.
test - Runs the unit tests.
validateSwagger - Validates the swagger specification.

Other tasks
-----------
core:cleanEclipseClasspath
core:cleanEclipseJdt
core:cleanEclipseProject
core:cleanIdeaModule
core:compileJava - Compiles main Java source.
core:compileTestJava - Compiles test Java source.
core:dependencyManagement
core:dependencyReport - Generates a report about your library dependencies.
core:eclipseClasspath - Generates the Eclipse classpath file.
core:eclipseJdt - Generates the Eclipse JDT settings file.
core:eclipseProject - Generates the Eclipse project file.
core:htmlDependencyReport - Generates an HTML report about your library dependencies.
core:ideaModule - Generates IDEA module files (IML)
ideaProject - Generates IDEA project file (IPR)
ideaWorkspace - Generates an IDEA workspace file (IWS)
core:installLombok
easy-cover-api:installLombok
easy-cover-service:installLombok
core:jacocoTestReport
core:processResources - Processes main resources.
core:processTestResources - Processes test resources.
core:propertyReport - Generates a report about your properties.
core:taskReport - Generates a report about your tasks.
core:verifyLombok
easy-cover-api:verifyLombok
easy-cover-service:verifyLombok
wrapper
```

The lombok related tasks are:

```
core:installLombok
easy-cover-api:installLombok
easy-cover-service:installLombok
core:verifyLombok
easy-cover-api:verifyLombok
easy-cover-service:verifyLombok
```

Should they be called because the plugin injects its call into the build cycle? Could be.

**Comment by amarjeet** [comment]
I must re-iterate that somehow it is getting called only from within Jenkins. From CLI when I do a normal build, it just does not happen.

**Comment by franzbecker** [comment]
Did you apply the --all option? Sorry but I don't have access to a computer right now. What I need to see is the task dependencies.

**Comment by amarjeet** [comment]
I sure did.

**Comment by franzbecker** [comment]
Hi @amarjeet , do you still have this problem? I'm back from my vacation now ;)

I'm pretty sure that the issue is within your build configuration and not the plugin as this would affect the tests of this plugin as well (build tasks using this plugin are automatically executed and the `installLombok` task is not part of their lifecycle).

Did you include something like this:
```
build {
    dependsOn installLombok
}
```

And could you execute `gradle build --dry-run` on your project and paste the log here?

Also, you can use the following plugin to get a task tree in order to figure out the problem:
https://github.com/dorongold/gradle-task-tree
