### ISSUE TITLE
Add dependency to all sourceSets

### ISSUE THREAD

**Issue by BrainStone** [franzbecker/gradle-lombok#17]
Lombok should be added to all sourceSets.

**Comment by BrainStone** [comment]
Or at least have the possibility to add it to more sets.

**Comment by franzbecker** [comment]
Agreed, hope I'll have some time to work on it soon. If you're up for it you could also contribute, it's a lot of fun to work on Gradle plugins :)

**Comment by franzbecker** [comment]
@BrainStone is this still an issue for you?

**Comment by BrainStone** [comment]
No it isn't. My bad. I forgot to reply.

**Comment by DaMatrix** [comment]
Old issue, I know, but I'd be interested in this if it's not too much of a hassle to implement.

**Comment by franzbecker** [comment]
Shouldn't be so difficult but would be nice to somehow be able to customize the source sets it's applied to. I'll look into it soon.
