### ISSUE TITLE
How to use delombok with android app

### ISSUE THREAD

**Issue by ubaierbhat** [franzbecker/gradle-lombok#18]
Lombok doesn't work with may other library like dbFlow or dagger .. Kotlin also cannot see the code generated by lombok.  is it possible to use gradle-lombok and then delombok in an android project.

**Comment by franzbecker** [comment]
Could you give more details on your specific configuration?
Kotlin should be able to see the sources generated by Lombok, but it depends on a proper configuration (the Lombok steps must be performed before the Kotlin transpilation). Have you checked the guide here for configuring the Android studio? https://projectlombok.org/setup/android

**Comment by ubaierbhat** [comment]
I have configured lombok correctly. It works as expected but few libraries like dbflow do not see the code generated by lombok. e.g dbflow requires a default constructor and getters/setters for the models but it does not see the generated code (eg. ```@Data / @NoArgsConstructor``` ).. our way round it is to have package level access to the fields (bad practice) and write a no argument constructor manually. ( issue also discussed in [Is DBFlow compatible with Lombok](https://github.com/Raizlabs/DBFlow/issues/1084) ) 

Same problem is with Kotlin. Even though Android studio does not show any errors when we try to compile kotlin cannot access code generated by lombok  (related :  [Kotlin doesn't see Java Lombok accessors](https://stackoverflow.com/questions/35517325/kotlin-doesnt-see-java-lombok-accessors) )

**Comment by franzbecker** [comment]
Okay I see, Kotlin uses javac ... which kind of sucks. I know a similar language (Xtend) which has a better approach and is more transparent in this regards.

But unfortunately I don't really see what your question is regarding the plugin.

**Comment by ubaierbhat** [comment]
In the forums its suggested that we can try to delombok the project to make the code visible to kotlin or the other libraries. Is it possible to do this or will this be something too complicated? 

I guess I will have to drop the idea of using kotlin along with lombok.

**Comment by franzbecker** [comment]
Sounds like a reasonable idea. You can use this plugin but it only offers some basic support for it: https://github.com/franzbecker/gradle-lombok#delombok-support

The example only explains the usage for a delombok task in order to generate JavaDoc. In order to use it with Kotlin I could image that you need to add the delombok path as a source folder which might generate a conflict... but as I've never used Kotlin I can only guess. An alternative to Kotlin is [Xtend](https://www.eclipse.org/xtend/) but it doesn't have IntelliJ / Android Studio support yet :-/

**Comment by ubaierbhat** [comment]
I couldn't make it work 😞 . tbh I am not too familiar with gradle build scripts. It would require us delomboking the source code and using that as the output as source for rest of the build process. We decided to make a slow transition into lombok free code .. and then in future work add kotlin. 

Thank you for your reply. I guess you can close this issue... or keep it open incase some one else has a better solution
