### ISSUE TITLE
Cannot remove gradle-lombok plugin from project anymore

### ISSUE THREAD

**Issue by weickmanna** [franzbecker/gradle-lombok#22]
I decided to purge Lombok from one of our projects.

However, whenever I try to remove the gradle-lombok plugin, Gradle fails to execute any task, e.g. on gradle clean:

> Could not find method lombok() for arguments >
[build_58glb4xg0iaylnzz408l8404d$_run_closure2@54c44656] on root project 'myProject' of type org.gradle.api.Project.

The project had many releases (Maven publications) before.

Offending line of my build.gradle is the line "publications" in the following block:
```
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
```

However, that is just standard Gradle Maven publishing. How does it interact with the gradle-lombok plugin? I can see that all the pom.xml files of previous releases of my project have a lombok provided dependency. Can it no longer deal with it after removing the gradle-lombok plugin?

**Comment by franzbecker** [comment]
I don't see how they interact with each other and can't reproduce it... actually the Lombok dependency should not show up in your provided dependencies. How is your project configured?

**Comment by weickmanna** [comment]
Problem is gone, after I now restarted my computer. Seems like there was some broken cache.
Thanks for looking into this!
