### ISSUE TITLE
Add support for java-library plugin

### ISSUE THREAD

**Issue by mozinrat** [franzbecker/gradle-lombok#24]
Plugin doesn't work when we are using java-library plugin instead of java.

**Comment by franzbecker** [comment]
Hi @mozinrat,

finally had some time to do some refactoring and wrote a test for the java-library plugin.
It seems to work as expected out of the box.

The first thing the java-library plugin does is to apply the regular Java plugin ([source code](https://github.com/gradle/gradle/blob/da692a4c8b34295b5a3c24cc5a03800d17be06d6/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaLibraryPlugin.java#L53)).

Could you please provide some more details?
