### ISSUE TITLE
Update the wiki according to the gradle-plugin-3-0-0

### ISSUE THREAD

**Issue by Yukooo** [franzbecker/gradle-lombok#25]
After updating  a gradle-plugin up to the version 3-0-0 it fails while building the project

**Comment by franzbecker** [comment]
Hi @Yukooo,

I'm not able to get your point. There is no Gradle version 3.0.0. I've tested the plugin with Gradle 3.0 - works fine.
Could you please provide more information on your issue?

Thanks!

**Comment by Yukooo** [comment]
Yes It works, but from 3.0 we have to add 
`annotationProcessor 'org.projectlombok:lombok:1.16.18'
testAnnotationProcessor 'org.projectlombok:lombok:1.16.18'`
But there is said  nothing about it in the section "Usage"

PS
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - lombok-1.16.18.jar (org.projectlombok:lombok:1.16.18)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

**Comment by franzbecker** [comment]
I see you are developing for Android and are using the plugin `com.android.tools.build:gradle:3.0.0`. Thanks for the link. I will check if that can be automated or if it's better to include it in the documentation.

**Comment by franzbecker** [comment]
Tested it with IntelliJ and the `.idea/compiler.xml` looks like this when annotation processing is enabled:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CompilerConfiguration">
    <annotationProcessing>
      <profile default="true" name="Default" enabled="true" />
    </annotationProcessing>
  </component>
</project>
```

We could check if the `idea` plugin is applied on the project and if so hook into the configuration process and add this information as explained here: http://mrhaki.blogspot.de/2016/03/gradle-goodness-enable-compiler.html

**Comment by franzbecker** [comment]
@Yukooo does this work for you when using the newest version of the plugin (1.12)?

**Comment by Yukooo** [comment]
@franzbecker Unfortunately nothing is changed, even worse. I still have to declare + if I change version '1.11' with version '1.12' I get an error  "There is no package lombok..."

**Comment by franzbecker** [comment]
Can you give me a sample setup that reproduces this behavior? This would help me have a look at it.

**Comment by franzbecker** [comment]
Hi @Yukooo - is this still an issue for you? My guess would be that a lot of people developing for Android made the switch to Kotlin by now making this obsolete.
