### ISSUE TITLE
DelombokTask should set classpath in a way that allows it to be extended

### ISSUE THREAD

**Issue by BrainStone** [franzbecker/gradle-lombok#29]
Hi.

I tried creating a `DelombokTask` and adding some configurations to the `classpath`. But since the tasks sets the `classpath` instead of just adding to it, this gets overridden.

See: https://github.com/franzbecker/gradle-lombok/blob/master/src/main/groovy/io/franzbecker/gradle/lombok/task/DelombokTask.groovy#L30  
I sadly don't know enough about gradle to create a PR.

This likely also partially fixes #17 as that would make it possible manually adding the classpath entries.

**Comment by franzbecker** [comment]
Hi,

could you provide a small example that I could use for testing? That would help and make sure your use case is covered by the changes :)

**Comment by BrainStone** [comment]
Is a half complete build script enough or should I make small example repository?

**Comment by franzbecker** [comment]
Example repository would be great :)

**Comment by BrainStone** [comment]
Here you go: https://github.com/BrainStone/gradle-lombok-issue29-example

The classpath in the delombok task should work but it gets overriden by the line I provided. Instead it errors during the delombok task. Not like a build ending error, but still errors. And errors that can be avoided.

**Comment by franzbecker** [comment]
Just released version 1.11 - should work now :)

**Comment by BrainStone** [comment]
Works like a charm :)
