### ISSUE TITLE
Provide adoption for Kotlin DSL, especially for Delombok task. Provide samples.

### ISSUE THREAD

**Issue by soberich** [franzbecker/gradle-lombok#31]
Hi, 

having hard times figuring out is this plugin adopted for Kotlin DSL
Seems the task blow does just nothing
```
        withType<DelombokTask> {
            dependsOn("compileJava")
            val outputDir = File("$buildDir/delombok")
            outputs.dir(outputDir)
            java.sourceSets["main"].allSource.srcDirs.forEach {
                inputs.dir(it)
                args(it, "-d", outputDir)
            }
        }
```

**Comment by franzbecker** [comment]
Hi @soberich - is this still an issue for you?

Actually I've never seen a use-case for this as in my opinion if you can use Kotlin in your project you don't need Lombok. Except maybe for projects where for some company policies it's not allowed to write your "business code" in Kotlin.

**Comment by soberich** [comment]
@franzbecker I meant Gragle kotlin dsl. It's not about Kotlin in code. So, yes. Still it is.

**Comment by franzbecker** [comment]
@soberich I've created the "examples" folder recently where you can now find a Kotlin example (https://github.com/franzbecker/gradle-lombok/blob/master/examples/delombok-gradle-kotlin/build.gradle.kts). Hope that helps and if you have suggestions for improving the example please let me know.

**Comment by soberich** [comment]
@franzbecker Hey, thanks, very nice.
According to gradle kotlin-dsl guidelines you probably don't need that line https://github.com/franzbecker/gradle-lombok/blob/0c40d97d58b70b67821d5caeb8cafae3cf967b0c/examples/delombok-gradle-kotlin/build.gradle.kts#L6
It'll work just with `val delombok = by registering(DelombokTask::class) {...} `

as well as `getByName` invocation could be just `sourceSets["main"]`
Thanx again.

**Comment by franzbecker** [comment]
Thanks @soberich - I've updated the example accordingly.
