### ISSUE TITLE
Use new "compileOnly" dependency type

### ISSUE THREAD

**Issue by florian-negre-cbp** [franzbecker/gradle-lombok#32]
Hi,
When I use the task `war` on my project, Lombok is included in the package.
The fix done in #16 doesn't resolve my usecase.

To exclude the library, I have to write : `compileOnly 'org.projectlombok:lombok:1.16.20'` in my project.
I'm using Gradle 4.5

**Comment by franzbecker** [comment]
I agree it’s probably time to remove the Gradle 2.x support ;-) I’ll hopefully find time to do that as soon as possible.

**Comment by ubaierbhat** [comment]
I upgraded Gradle (3.0) and now I can't use Lombok annotations in JUnit Tests.  I think its related to dependency type. 

```
dependencies {
	compileOnly 'org.projectlombok:lombok:1.16.20'
        testCompileOnly 'org.projectlombok:lombok:1.16.20'
	annotationProcessor 'org.projectlombok:lombok:1.16.20'
}
```

**Comment by ubaierbhat** [comment]
We have to specify testAnnotationProcessor processor separately now.  
```
dependencies {
	compileOnly 'org.projectlombok:lombok:1.16.20'
        testCompileOnly 'org.projectlombok:lombok:1.16.20'
	annotationProcessor 'org.projectlombok:lombok:1.16.20'
        testAnnotationProcessor 'org.projectlombok:lombok:1.16.20'
}
```

**Comment by franzbecker** [comment]
Using the `compileOnly` scope directly introduced a few issues with the Delombok task. The proposed solution in #35 should fix this issue.
