### ISSUE TITLE
Maven Publish including Lombok in dependencies list

### ISSUE THREAD

**Issue by aikar** [franzbecker/gradle-lombok#37]
See: https://github.com/aikar/db/blob/bf79fccb30aa584c1dede3106b7bc7cfc6573ce2/build.gradle
When I publish to maven, Lombok is listed as a dependency.

This causes users of my library to then pick up the lombok dependency transitively and it gets shaded into their release.

Generated POM: https://gist.github.com/9c351180f8363d1a1fd866989aee2e83

This plugin appears to use its own "lombok" configuration name. I've read somewhere that the maven publish plugin knows to ignore compileOnly deps. Would moving this plugin to compileOnly instead of its own fix it?

**Comment by aikar** [comment]
switching to maven plugin allowed me to force it to provided, re https://github.com/aikar/db/blob/master/build.gradle#L36

But that was more so a workaround than solving this root issue.

**Comment by franzbecker** [comment]
https://github.com/franzbecker/gradle-lombok/pull/43 resolves this issue 🎉
