### ISSUE TITLE
RFE: Expose lombok dependency coordinates as an option

### ISSUE THREAD

**Issue by mmoayyed** [franzbecker/gradle-lombok#41]
Today, the plugin here adds the lombok dependency using its own coordinates:

```groovy
        project.afterEvaluate {
            project.dependencies.add(
                    LOMBOK_CONFIGURATION_NAME,
                    "org.projectlombok:lombok:${project.lombok.version}",
                    {
                        transitive = false
                    }
            )
        }
```

Could I submit a pull request to turn the hard-coded coordinates into one that is defined by an option, and that the option has the current coordinates as defaults? The idea would be to expose the option inside `LombokPluginExtension` and then add it as it's normally done today. 

I am in the process of experimenting with lombok in order to write a few custom extensions and the easiest way to do this would be to fork lombok (given there is no official extension mechanism AFAIK). With a forked lombok repository, I'd like to be able to use that fork with the plugin under my own coordinates. If the proposed option sounds good to you, I'd be happy to close this issue and follow-up with a pull request to get this done.

**Comment by franzbecker** [comment]
Sure please go ahead 👍

**Comment by franzbecker** [comment]
Please note that I'm refactoring the way the dependency is added, see https://github.com/franzbecker/gradle-lombok/pull/43

**Comment by mmoayyed** [comment]
Wonderful. I'll proceed with the changes and pull request shortly. Thank you. 

Closing this for now.
