### ISSUE TITLE
Where can i find the SHA-256 for the latest Lombok Version 1.18.2 ?

### ISSUE THREAD

**Issue by fioritonicolas** [franzbecker/gradle-lombok#49]
Sorry if is a silly question, but i´m struggling to find the SHA-256 for the latest lombok version.

Thanks.

**Comment by franzbecker** [comment]
You can download the latest Lombok version here: https://projectlombok.org/download and then execute the following command on it (Mac / Unix):

```
> shasum -a 256 lombok.jar 
f13db210efa2092a58bb7befce58ffa502e5fefc5e1099f45007074008756bc0  lombok.jar
```

This way you can verify that the JAR published on the project's website is the same as the one retrieved through your configured Maven repository.

Hope that helps!

**Comment by fioritonicolas** [comment]
Awesome, thank you very much.
