### ISSUE TITLE
Using edge or custom lombok version

### ISSUE THREAD

**Issue by victorwss** [franzbecker/gradle-lombok#51]
Sorry if this question is silly, but I just discovered this project today. After a quick look at the sources, it seems that there is no way to use a lombok edge version.

In some rare occasions, I also hack around lombok sources in order to try to fix bugs or propose new features. So, it is important for me to be able to test those custom versions easily.

Until now, I used this to allow the use of an edge or custom version of lombok:

```groovy
ext.versionLombok = "edge"
//ext.versionLombok = "1.18.2"

dependencies {
    if (versionLombok != "edge") {
        annotationProcessor group: 'org.projectlombok', name: 'lombok', version: versionLombok
        compileOnly group: 'org.projectlombok', name: 'lombok', version: versionLombok
        testAnnotationProcessor group: 'org.projectlombok', name: 'lombok', version: versionLombok
        testCompileOnly group: 'org.projectlombok', name: 'lombok', version: versionLombok
    } else {
        annotationProcessor files("libs/lombok-edge.jar")
        compileOnly files("libs/lombok-edge.jar")
        testAnnotationProcessor files("libs/lombok-edge.jar")
        testCompileOnly files("libs/lombok-edge.jar")
    }
}
```

However, I see no way of doing something similar to this when using this plugin. It would be nice if there was some way to tell the plugin to "*just use this JAR as my lombok*".

BTW, if someone decides to use an edge or custom lombok version that is lying somewhere in some folder, then there is no need to check SHA-256. By being an edge or custom version, there aren't no guarantees whatsoever anyway.

**Comment by franzbecker** [comment]
Thank you for suggesting this feature. I haven't had time for this one so far.
There has been an attempt to do this by a contributor previously: https://github.com/franzbecker/gradle-lombok/pull/44/

**Comment by franzbecker** [comment]
@victorwss is this still relevant for you?

**Comment by franzbecker** [comment]
Closed due to inactivity.
