### ISSUE TITLE
Plugin breaks annotation processing during compilation (since 1.12)

### ISSUE THREAD

**Issue by BrainStone** [franzbecker/gradle-lombok#53]
I've noticed that the versions 1.12 through 1.14 are breaking annotation processing during compilation.

An example where I came across this issue is while trying to develop a Sponge plugin. The `@Plugin` annotation causes the jar to have a `mcmod.info` file included. When I compile with gradle-lombok 1.11, everything works as intended, but with 1.12-1.14 the annotation processing is broken and the file is missing from the jar.

I've created a minimal test project that showcases the issue.
I've also included the SpongeGradle plugin. It's commented out, but I included it just in case having it enabled also shouldn't break it. Having it enabled should yield the exact same result as having it disabled, the way I set it up.

[SpongeTest.zip](https://github.com/franzbecker/gradle-lombok/files/2408899/SpongeTest.zip)

**Comment by franzbecker** [comment]
Is this still an issue for you?

**Comment by franzbecker** [comment]
Hi @BrainStone . I downloaded your example and can see that it's not working. Unfortunately I don't understand exactly what this Sponge plugin does.

The reason we had this breaking change (from 1.12 - should have gone to 2.0 then, sorry for that) is that Gradle introduced a new mechanism of registering annotation processors. On a quick look it seems that the Sponge plugin should adapt as well as this does not look like the way to go (at least to me): https://github.com/SpongePowered/SpongeGradle/blob/0.9.0/src/main/groovy/org/spongepowered/gradle/plugin/SpongePluginBasePlugin.groovy

They have an open issue supporting Gradle 5, maybe once this is resolved you can upgrade the Lombok plugin again. See https://github.com/SpongePowered/SpongeGradle/issues/19

Sorry for the inconvenience.
