### ISSUE TITLE
Gradle 5.0-rc-1/IntelliJ Import Problem

### ISSUE THREAD

**Issue by sghill** [franzbecker/gradle-lombok#56]
Hello,

Just wanted to give you a heads up that I ran into [IDEA-201974](https://youtrack.jetbrains.com/issue/IDEA-201974) when upgrading a project that uses this plugin from Gradle 4.10.2 -> 5.0-rc-1 in case anyone else runs into trouble with Gradle 5.

There seems to be a problem with IntelliJ seeing dependencies for compilation that are present on these configurations at the same time: `compileOnly`, `testCompileOnly`, and `annotationProcessor`.

**Comment by alex-hall** [comment]
Still not working with eclipse 2018.3.1, I had to remove the plugin and manually add: 

    //Lombok. Intellij can't figure out how to use the lombok gradle plugin as of 2018.3.1 :( 
    annotationProcessor "org.projectlombok:lombok:1.18.4"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.4"
    compileOnly "org.projectlombok:lombok:1.18.4"
    testCompileOnly "org.projectlombok:lombok:1.18.4"

EDIT FOR CLARITY: 

The plugin compiles just fine and runs from a command line perspective, but intellij can't make heads of tails out of any imports or annotations.

**Comment by alex-hall** [comment]
This slightly less verbose version also works: 
```
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    implementation "org.projectlombok:lombok:$lombokVersion"
```

**Comment by hhktseng** [comment]
> This slightly less verbose version also works:
> 
> ```
>     annotationProcessor "org.projectlombok:lombok:$lombokVersion"
>     implementation "org.projectlombok:lombok:$lombokVersion"
> ```

you only need 
```
    implementation "org.projectlombok:lombok:$lombokVersion"
```

this is right now a "hackish" approach to integrate with intelliJ

**Comment by franzbecker** [comment]
Yeah we also had this problem before which is hard to fix on this end.
I just tried it out on 2018.3 with the newest IntelliJ Lombok plugin "v0.23-2018.3" and it worked just fine. Could you double check please?

**Comment by hhktseng** [comment]
using official recommendations:

```
plugins {
    id 'io.franzbecker.gradle-lombok' version '1.14'
}

lombok {
    version = '1.18.4'
    sha256 = ""
}
```

without

> implementation group: 'org.projectlombok', name: 'lombok', version: '1.18.4'

Gradle Version: 5.1.1
Lombok Gradle Plugin: v0.23-2018.2
IntelliJ Version: 2018.2.5

this issue still exists

**Comment by franzbecker** [comment]
Thanks for the prompt reply - how about 2018.3 ?

**Comment by franzbecker** [comment]
I double checked and with 
- IntelliJ Version: 2018.3
- IntelliJ Lombok plugin: v0.23-2018.3
and the problem seems to be gone.

To my understanding this was not an issue of this Gradle plugin. Please reopen if you disagree and problems remain.

**Comment by chpasha** [comment]
Does this plugin adds all needed annotations automatically when used with android project or do I have to declare some/all of them manually? The documentation says I can use annotations straight away after applying plugin which is actually **not** the case with android project in IDEA 2019.3.3 / Android Studio 3.5.2 and android gradle plugin 3.5.3 + gradle 5  and gradle lombok version 3.3.0

**Comment by franzbecker** [comment]
Which documentation are you referring to?

You will need to perform the following steps as well:

- Go to File > Settings > Plugins
- Click on Browse repositories...
- Search for Lombok Plugin
- Click on Install plugin
- Restart Android Studio

(copied from https://projectlombok.org/setup/android)

**Comment by chpasha** [comment]
I'm referring the documentation of this plugin which states that 
> After applying the plugin, the Lombok annotations can be used directly in any Java code

and

>this plugin adds the Lombok dependency to compileOnly and testCompileOnly. Starting with Gradle 4.6 also annotationProcessor and testAnnotationProcessor

which doesn't seem to work. I have Lombok Plugin already installed but after applying your plugin I cannot use Lombok annotations since lombok appear to be **not** on classpath. Adding Lombok dependencies directly does work

**Comment by franzbecker** [comment]
That sounds indeed odd. Can you give me more details to go on? Ideally some reproducible example. 
And can you build the project on the command line or does it not work there as well?

Unfortunately, I can't give any Android Studio specific support. I would recommend using Kotlin for Android.

**Comment by chpasha** [comment]
>Can you give me more details to go on?

it is reproducible for me on android studio 3.5.2 and in IDEA 2019.3.3 on an empty project created with wizard after applying recommended configuration for plugin. Android Gradle Plugin is 3.5.3, gradle version used by default was 5.4.1 but I also tried the 5.6.x and 6.x

>And can you build the project on the command line or does it not work there as well?

doesn't work as well, producing "package lombok does not exist"
