### ISSUE TITLE
Tagging gradle-lombok releases?

### ISSUE THREAD

**Issue by rud** [franzbecker/gradle-lombok#57]
Looking at the list of tagged releases at https://github.com/franzbecker/gradle-lombok/releases, the most recent versions seem to be missing. Maybe something has broken in the release procedure? 

Just thought I'd mention it. Thank you for a neat tool 👍

**Comment by franzbecker** [comment]
Thanks for the hint - the tags exist they just aren't marked as release on the Github UI. I did this manually for previous versions but didn't do it for the recent ones.

For example: https://github.com/franzbecker/gradle-lombok/releases/tag/v1.14

**Comment by rud** [comment]
Alright 👍
