### ISSUE TITLE
gradle-lombok doesn't work in spring boot 2.1.3

### ISSUE THREAD

**Issue by hendisantika** [franzbecker/gradle-lombok#63]
I am using Spring Boot 2.1.3
but why gradle-lombok doesn't work in spring boot 2.1.3?

Any suggest?

Thanks

**Comment by legart** [comment]
I have plenty of projects with Spring Boot 2.1.3 that use gradle-lombok. What error do you get?

**Comment by hendisantika** [comment]
should I post my github link here?

https://gitlab.com/hendisantika/springboot-auth-server

**Comment by franzbecker** [comment]
In your example there is a compile error:
```
import org.springframework.stereotype.Controller;

...

@Controller
@Slf4j
public class LogoutController<Controller> {
```

The `@Controller` is an annotation and should not be used as a type parameter as you did here.

Try replacing this by:
```
@Controller
@Slf4j
public class LogoutController {
```

And then your example compiles (and the builds fails at some other point).
See also: https://spring.io/guides/gs/serving-web-content/

Hope that helps.
