### ISSUE TITLE
Configuration by convention for plugin or global lombok options to specify version and other config

### ISSUE THREAD

**Issue by ieugen** [franzbecker/gradle-lombok#65]
Hi,

Right now I can configure my lombok version per module which is nice. 
However most of my projects in a multi module build have the same lombok version.

It would be great if this module could add a way to configure all lombok plugins to use the same lombok version, without having to specify the `lombok` configuraion block in all modules.

I think the plugin could check if some properties are defined or the `lombok.config` file is defined and contains a version property ?! 

I would like to avoid configuring lombok in every module since the config / version is the same for all of my modules: 

```
lombok {
 version = ...
}
```

**Comment by franzbecker** [comment]
Hi there,

from what you are describing it seems to be as this should solve your
problem:

https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:subproject_configuration

Simply configure the Lombok plugin in an allprojects / subprojects closure.

Hope that helps!

**Comment by franzbecker** [comment]
On further thought I think this is worth investigating.

My thoughts for solving that:
- If the plugin is added to a root project of a multi-module project than it adds the dependency to all subprojects which have a JavaPlugin applied
- installLombok and verifyLombok task should be only applied at the root level

**Comment by ieugen** [comment]
Sounds reasonable. Please take into account the ability to disable plugin application and to configure it differently for other projects than the root project.

**Comment by franzbecker** [comment]
@ieugen I just had another look at it and wondered about having different Lombok versions on different modules as you described above. Could you please elaborate in which scenarios this makes sense for you? 

For the `installLombok` this doesn't really work since you would want to install a single Lombok version into Eclipse, right? (I use IntelliJ now nowadays so I wouldn't know).

**Comment by ieugen** [comment]
Hi, 

Honestly I can't see any (unless you are working on lombok itself and wish to test other versions ?!).

It might happen that you wish to have other `configurations` for lombok on different projects. Stuff like:
- lombok.anyConstructor.addConstructorProperties ?and similar that might make sense for a library author ?! .

I use IntelliJ as well.

**Comment by franzbecker** [comment]
I would close this as won't fix as I moved the plugin to maintenance mode. Are you interested in contributing towards this feature?

**Comment by ieugen** [comment]
Go ahead, close it. I moved to using Clojure. Trimis de pe smartphone-ul meu Samsung Galaxy.
-------- Mesaj original --------De la: Franz Becker <notifications@github.com> Date: 10.05.2020  15:36  (GMT+02:00) Către: franzbecker/gradle-lombok <gradle-lombok@noreply.github.com> Cc: Eugen Stan <eugen@ieugen.ro>, Mention <mention@noreply.github.com> Subiect: Re: [franzbecker/gradle-lombok] Configuration by convention for plugin or global lombok options to specify version and other config (#65) 
I would close this as won't fix as I moved the plugin to maintenance mode. Are you interested in contributing towards this feature?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/franzbecker/gradle-lombok/issues/65#issuecomment-626321754",
"url": "https://github.com/franzbecker/gradle-lombok/issues/65#issuecomment-626321754",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ieugen** [comment]
No. I moved to Clojure.
