### ISSUE TITLE
Default delombok task doesn't work by default with modern implementation dependencies

### ISSUE THREAD

**Issue by chadlwilson** [franzbecker/gradle-lombok#68]
**Problem**
The default configuration doesn't build the JavaExec classpath correctly if you use modern Gradle `implementation` dependencies; as opposed to the legacy/deprecated `compile` dependencies from Gradle 2.x.

**Workaround**
Extend the classpath like the below
```
task delombok(type: io.franzbecker.gradle.lombok.task.DelombokTask, dependsOn: compileJava) {
    classpath += project.configurations.compileClasspath
    //...
```

**Comment by franzbecker** [comment]
I've release your change as v3.0.0. Thanks again 👍

**Comment by chadlwilson** [comment]
Wow, `3.0.0` - big move ;-)
