### ISSUE TITLE
Delombok classpath is incorrect

### ISSUE THREAD

**Issue by tterrag1098** [franzbecker/gradle-lombok#7]
I'm back! This time, trying to generate some javadocs against delomboked code. Seems that the classpath isn't quite right. I think you need to add the compile classpath to the delombok task as well. As it is a few of my libraries are missing and it fails.

**Comment by franzbecker** [comment]
Thanks for shaking out the bugs :-)
I'll have time to fix it tomorrow, latest.

Do you have a minimal example that requires a library from the compile classpath to delombok? Then I would add that to the test suite.

**Comment by tterrag1098** [comment]
I don't unfortunately, my project uses quite a few libs

**Comment by franzbecker** [comment]
Issue is fixed with version `1.5`, the compile classpath is now added to the `DelombokTask`.

**Comment by tterrag1098** [comment]
Working perfectly now! Thanks

**Comment by franzbecker** [comment]
Good to know! If you're missing a feature or have any other suggestions feel free to file more issues :)

**Comment by tterrag1098** [comment]
Nope, seems to be working great, I have it set up now to delombok prior to building the javadoc and it works like a charm :)
