### ISSUE TITLE
Cannot run delombok task

### ISSUE THREAD

**Issue by aram535** [franzbecker/gradle-lombok#70]
I added the plugin to my build.gradle (1st):
```
plugins { 
    id 'io.franzbecker.gradle-lombok' version '3.0.0'
    id 'java'
    ....
```

Apply the delombok.gradle, and I get the following error.  I also tried adding a "buildScript" section above the import to see if that would resolve it.

```
$ ./gradlew javadoc

FAILURE: Build failed with an exception.

* Where:
Script 'E:\src\didata\java\java-github-api\gradle\delombok.gradle' line: 7

* What went wrong:
Could not compile script '...\project\gradle\delombok.gradle'.
> startup failed:
  script '....project\gradle\delombok.gradle': 7: unable to resolve class io.franzbecker.gradle.lombok.task.DelombokTask
   @ line 7, column 1.
     import io.franzbecker.gradle.lombok.task.DelombokTask
     ^

  1 error


```

**Comment by franzbecker** [comment]
Can you provide a quick standalone example so I can have a look at it?

There is an example here:
https://github.com/franzbecker/gradle-lombok/blob/master/examples/delombok-gradle-groovy/build.gradle

The difference might be that it's added using the legacy mechanism:
https://github.com/franzbecker/gradle-lombok/blob/master/examples/build.gradle
