### ISSUE TITLE
How to pass --nocopy option to delombok task

### ISSUE THREAD

**Issue by a1730** [franzbecker/gradle-lombok#73]
Hi,
What is the recommended way to pass lombok options to the delombok task?
Javadoc task is failing on delombok files because of non-java types. 
However, there is a lombok option --nocopy that solves this issue if we can figure out how to pass the option through to the plugin.
Thank you.

**Comment by franzbecker** [comment]
Could you be more specific, e.g. provide the definition of the delombok task you are currently using? 

Please try appending the argument in the task definition, e.g. https://github.com/franzbecker/gradle-lombok/blob/master/examples/delombok-gradle-groovy/build.gradle#L8 or https://github.com/franzbecker/gradle-lombok/blob/master/examples/delombok-gradle-kotlin/build.gradle.kts#L11

Might just be adding an `-n` flag (see https://github.com/rzwitserloot/lombok/blob/master/src/delombok/lombok/delombok/Delombok.java#L156). But I never used that.

**Comment by a1730** [comment]
FacePalm 🤦... Right under my nose:)
Thank you.
