### ISSUE TITLE
Incompatible with the java-test-fixtures plugin

### ISSUE THREAD

**Issue by Christiaan676** [franzbecker/gradle-lombok#78]
When using lombok annotations in src/testFixtures the compiler is unable to resolve the annotations. Manually adding the dependency fixes this.

```
dependencies {
    testFixturesCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testFixturesAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}
```

**Comment by franzbecker** [comment]
Hey @Christiaan676 👋 this project is no longer being actively developed.
You can still contribute fixes, however. Please feel free to open a PR.
