### ISSUE TITLE
Suggestion: Automatic IDEA installation

### ISSUE THREAD

**Issue by tterrag1098** [franzbecker/gradle-lombok#8]
This would be a HUGE help to me, as most people cloning my project aren't even using eclipse. I have no idea how possible this is, but if it is doable I can say that it would be an amazing feature to have,

**Comment by franzbecker** [comment]
As I understand it IntelliJ is not officially supported by Lombok, one has to install the IntelliJ plugin for it: https://github.com/mplushnikov/lombok-intellij-plugin

For the Eclipse installation, this gradle plugin simply calls the official Lombok installer (and does a validation of the JAR upfront).

Hence, supporting an IntelliJ installer is, unfortunately, out of scope for this plugin. Could you help your users by providing a link to the plugin?
